name: static code analysis

on:
  push:
  schedule:
    - cron: '0 0 * * 1'

env:
  SCAN_IMG:
    yes-docker-local.artifactory.in.yubico.org/static-code-analysis/c:v1
  COMPILE_DEPS: "libcurl4-openssl-dev libusb-1.0-0-dev libedit-dev"
  PVS_IGNORE_WARNINGS: "V571,V1037"
  SECRET: ${{ secrets.ARTIFACTORY_READER_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Scan and fail if warnings
      run: |
        if [ "${SECRET}" != "" ]; then
          docker login yes-docker-local.artifactory.in.yubico.org/ \
            -u svc-static-code-analysis-reader -p ${SECRET}
          docker pull ${SCAN_IMG}
          docker run -v${PWD}:/k -e COMPILE_DEPS="${COMPILE_DEPS}" \
            -e PROJECT_NAME=${GITHUB_REPOSITORY#Yubico/} \
            -e PVS_IGNORE_WARNINGS=${PVS_IGNORE_WARNINGS} -t ${SCAN_IMG}
        fi

    - uses: actions/upload-artifact@master
      if: failure()
      with:
        name: suppression_files
        path: suppression_files
